

spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://festival-holic-db.cfifsc0ra5hp.ap-northeast-2.rds.amazonaws.com:3306/festival_holic_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: festivalholic
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
server:
  port: 8083

cloud:
  aws:
    s3:
      bucket: fh-image-bucket
      stack.auto: false
    region.static: ap-northeast-2

    credentials:
      accessKey:
      secretKey:
